### ISSUE TITLE
Outdated as of latest NPCMapLocations

### ISSUE THREAD

**Issue by Violet-Vibes** [DOOMustard/StardewValley-NPCMapLocations-Addon#1]
As it changes how tracking etc is handled, see https://github.com/bbpak/stardew-valley-mods/tree/main/NPCMapLocations#custom-npcs

**Comment by DOOMustard** [comment]
This update to NPCMapLocations does make this addon obsolete in its current form. 
this new method involves cross-mod communication.
I could update this to be its own mod but I think I'd be better off contacting the mod creators and helping them add it to their own mods,
hopefully in a week or two most mods can add their own support through this new method.
I've updated the readme to reflect this so I'm going to set this issue to fixed
